[game]
desc             = """üíª –ú–æ—â–Ω—ã–π —Ö–æ—Å—Ç–∏–Ω–≥.
üé® –ê–≤—Ç–æ—Ä—Å–∫–∏–π –∫–æ–Ω—Ç–µ–Ω—Ç.
üìà –£–Ω–∏–∫–∞–ª—å–Ω–∞—è —Å–∏—Å—Ç–µ–º–∞ –Ω–∞–≤—ã–∫–æ–≤
üìö –°–æ–±—Å—Ç–≤–µ–Ω–Ω–∞—è –≤–∏–∫–∏, –∫–æ—Ä–ø–æ—Ä–∞—Ç–∏–≤–Ω—ã–π –∑–∞–∫–æ–Ω –∏ –°–†–ü.
üåü –ë–∞–ª–∞–Ω—Å —Ä–æ–ª–µ–≤–æ–π –∏–≥—Ä—ã –∏ –≤–µ—Å–µ–ª—å—è ‚Äì —Å—Ç–∞–Ω—å —á–∞—Å—Ç—å—é —É–Ω–∏–∫–∞–ª—å–Ω–æ–≥–æ —Å–æ–æ–±—â–µ—Å—Ç–≤–∞!"""
lobbyenabled     = true
lobbyduration = 180
soft_max_players = 40
panic_bunker.enabled = false
#panic_bunker.disable_with_admins = true
#panic_bunker.enable_without_admins = true
#panic_bunker.show_reason = true
#panic_bunker.min_overall_minutes = 60
#panic_bunker.custom_reason = "–í –Ω–∞—Å—Ç–æ—è—â–∏–π –º–æ–º–µ–Ω—Ç –Ω–µ—Ç –º–æ–¥–µ—Ä–∞—Ç–æ—Ä–æ–≤, –∞ –≤—ã –Ω–µ –Ω–∞–∏–≥—Ä–∞–ª–∏ –¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ–≥–æ –∫–æ–ª–∏—á–µ—Å—Ç–≤–∞ –º–∏–Ω—É—Ç (60) –Ω–∞ –Ω–∞—à–µ–º —Å–µ—Ä–≤–µ—Ä–µ."
contraband_examine = false

[hub]
tags = "lang:ru,region:eu_e,rp:med"
advertise = true

[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = true

[net]
tickrate = 32
max_connections = 100

[infolinks]
discord = "https://discord.gg/sRSGDyGPw2"
wiki = "https://vanilla-station.ru/"
appeal = "https://discord.com/channels/1236324156165980311/1236381848909910126"
github = "https://github.com/VanillaStation14/VanillaStation"
bug_report = "https://discord.com/channels/1236324156165980311/1271239142944280671"

[vote]
restart_required_ratio = 0.7
restart_enabled = false
map_enabled = true
timermap = 45

[chat]
rate_limit_count = 3
rate_limit_period = 3

[shuttle]
auto_call_time = 100
auto_call_extension_time = 30
arrivals_map = "/Maps/Misc/corvax_terminal.yml"
emergency_early_launch_allowed = true

[biomass]
easy_mode = false

[netres]
limit = 10.0

[admin]
deadmin_on_join = true
new_player_threshold = 300
alert.min_players_sharing_connection = 2
new_player_join_sound = true

[ahelp]
admin_prefix = 1
rate_limit_count = 3
rate_limit_period = 6

[atmos]
space_wind = true

[worldgen]
enabled = true

[auth]
mode = 1

[viewport]
maximum_width = 29

[server]
rules_file = "VanillaRulset"

[replay]
auto_record = true

[discord]
rich_main_icon_id = "vanilla-station"
