- type: job
  id: MedicalIntern
  name: job-name-intern
  description: job-description-intern
  playTimeTracker: JobMedicalIntern
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 108000 #30 hrs # Corvax-RoleTime
      inverted: true # stop playing intern if you're good at med!
  startingGear: MedicalInternGear
  icon: "JobIconMedicalIntern"
  supervisors: job-supervisors-medicine
  canBeAntag: false
  access:
  - Medical
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skill
        PilotingLevel: 0
        RangeWeaponLevel: 0
        MeleeWeaponLevel: 0
        MedicineLevel: 2
        ChemistryLevel: 2
        EngineeringLevel: 0
        BuildingLevel: 0
        ResearchLevel: 0
        InstrumentationLevel: 0
      - type: AddSkillPoints
        Points: 6

- type: startingGear
  id: MedicalInternGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: MedicalInternPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    #pocket2: BookMedicalReferenceBook
  #storage:
    #back:
    #- Stuff
