- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 360000 #100 hrs # Vanilla-RoleTime
    - !type:AgeRequirement
      requiredAge: 28
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: Skill
        PilotingLevel: 3
        RangeWeaponLevel: 3
        MeleeWeaponLevel: 3
        MedicineLevel: 1
        ChemistryLevel: 0
        EngineeringLevel: 1
        BuildingLevel: 0
        ResearchLevel: 0
        InstrumentationLevel: 0
      - type: CommandStaff
      - type: AddSkillPoints
        Points: 6

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    # gloves: ClothingHandsGlovesCaptain #vanilla-loadouts
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    # - StationCharter
