# СПРАВКА ПО ПОВОДУ РАБОТЫ guaranteedSpawn & specForceSpawn
#
# specForceSpawn считает количество ролей для спавна по формуле (Количество игроков + maxRolesAmount) / maxRolesAmount,
# потому на 20 человек на сервере в обычных условиях заспавнится 3 оперативника.
#
# guaranteedSpawn спавнит все роли из своего списка, не смотря на какие-либо ограничения по игрокам.
#
# Это значит, что в guaranteedSpawn лучше всего указывать только Уникальные и случайные бонусные роли.
#
# Учитывайте это при построении новых прототипов или изменении старых.

# ERT
- type: SpecForceTeam
  id: ERT
  specForceName: spec-forces-system-ert-security
  shuttlePath: Maps/Shuttles/dart.yml
  spawnMarker: MarkerSpecforce
  announcementText: spec-forces-system-ertcall-annonce
  announcementTitle: spec-forces-system-ertcall-title
  sound:
    path: /Audio/Corvax/Adminbuse/yesert.ogg
    params:
      volume: -4
  maxRolesAmount: 8
  raffleConfig:
    settings: short
  guaranteedSpawn:
    - id: SpawnMobHumanERTLeader
  specForceSpawn:
    - id: SpawnMobHumanERTSecurity
