- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 #20 hrs # Corvax-RoleTime
    - !type:AgeRequirement
      requiredAge: 25
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Detective
  - Cryogenics
  - External
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skill
        PilotingLevel: 0
        RangeWeaponLevel: 2
        MeleeWeaponLevel: 1
        MedicineLevel: 2
        ChemistryLevel: 2
        EngineeringLevel: 2
        BuildingLevel: 0
        ResearchLevel: 1
        InstrumentationLevel: 0
      - type: AddSkillPoints
        Points: 6
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterFilled
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner
