- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 #10 hrs # Corvax-RoleTime
    - !type:AgeRequirement
      requiredAge: 20
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skill
        MedicineLevel: 1
        RangeWeaponLevel: 3
        PilotingLevel: 3
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol
