- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 #10 hrs # Corvax-RoleTime
    - !type:AgeRequirement
      requiredAge: 20
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: Speech
        speechSounds: Soldier
        soundCooldownTime: 0.1
      - type: TriggerOnMobstateChange
        mobState:
        - Critical
      - type: EmitSoundOnTrigger
        sound:
          collection: SoldierDeath
          params:
            volume: -4
      - type: Skill
        PilotingLevel: 3
        RangeWeaponLevel: 3
        MeleeWeaponLevel: 3
        MedicineLevel: 1
        ChemistryLevel: 0
        EngineeringLevel: 0
        BuildingLevel: 0
        ResearchLevel: 0
        InstrumentationLevel: 0
      - type: AddSkillPoints
        Points: 6


- type: startingGear
  id: SecurityOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol
