contact_links:
  - name: Предложение
    url: https://discord.gg/vanilla-station
    about: Свои предложения можете оставлять в соответствующем канале Discord.
  - name: Сообщить об уязвимости
    url: https://discord.gg/vanilla-station
    about: Пожалуйста, сообщайте о серьезных эксплойтах и уязвимостях безопасности thefuckmybrain (287950407680917504) в Discord.
