- type: job
  id: TechnicalAssistant
  name: job-name-technical-assistant
  description: job-description-technical-assistant
  playTimeTracker: JobTechnicalAssistant
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200 #2 hrs # Vanilla-RoleTime
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 108000 #30 hrs # Vanilla-RoleTime
      inverted: true # stop playing intern if you're good at engineering!
    - !type:AgeRequirement
      requiredAge: 	20
  startingGear: TechnicalAssistantGear
  icon: "JobIconTechnicalAssistant"
  supervisors: job-supervisors-engineering
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - External
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skill
        PilotingLevel: 1
        RangeWeaponLevel: 0
        MeleeWeaponLevel: 1
        MedicineLevel: 0
        ChemistryLevel: 0
        EngineeringLevel: 2
        BuildingLevel: 2
        ResearchLevel: 0
        InstrumentationLevel: 1
      - type: AddSkillPoints
        Points: 6

- type: startingGear
  id: TechnicalAssistantGear
  equipment:
    shoes: ClothingShoesBootsWork
    id: TechnicalAssistantPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
    pocket2: BookEngineersHandbook
  #storage:
    #back:
    #- Stuff
