- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 36000 #10 hrs # Vanilla-RoleTime
    - !type:AgeRequirement
      requiredAge: 23
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Skill
        PilotingLevel: 3
        RangeWeaponLevel: 1
        MeleeWeaponLevel: 1
        MedicineLevel: 1
        ChemistryLevel: 1
        EngineeringLevel: 1
        BuildingLevel: 1
        ResearchLevel: 0
        InstrumentationLevel: 1
      - type: AddSkillPoints
        Points: 6
        
- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
