- type: job
  id: Bartender
  name: job-name-bartender
  description: job-description-bartender
  playTimeTracker: JobBartender
  startingGear: BartenderGear
  icon: "JobIconBartender"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Bar
  extendedAccess:
  - Kitchen
  - Hydroponics
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skill
        PilotingLevel: 0
        RangeWeaponLevel: 2
        MeleeWeaponLevel: 0
        MedicineLevel: 0
        ChemistryLevel: 0
        EngineeringLevel: 0
        BuildingLevel: 0
        ResearchLevel: 0
        InstrumentationLevel: 0
      - type: AddSkillPoints
        Points: 6

- type: startingGear
  id: BartenderGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: BartenderPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff
