- type: job
  id: Chef
  name: job-name-chef
  description: job-description-chef
  playTimeTracker: JobChef
  startingGear: ChefGear
  icon: "JobIconChef"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Kitchen
  extendedAccess:
  - Hydroponics
  - Bar
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skill
      PilotingLevel: 0
      RangeWeaponLevel: 0
      MeleeWeaponLevel: 2
      MedicineLevel: 0
      ChemistryLevel: 0
      EngineeringLevel: 0
      BuildingLevel: 0
      ResearchLevel: 0
      InstrumentationLevel: 0
    - type: AddSkillPoints
      Points: 6

- type: startingGear
  id: ChefGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChefPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltChefFilled
  #storage:
    #back:
    #- Stuff
