# No idea why it's in sci but we ball.
- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 #20 hrs
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-rd
  jobEntity: StationAiBrain
  applyTraits: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skill
        MedicineLevel: 3
        ChemistryLevel: 3

- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 #20 hrs
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgGeneric
  applyTraits: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skill
        MedicineLevel: 3
        ChemistryLevel: 3
